theme: jekyll-theme-cayman
title: [Workshop on Extraction and Evaluation of Knowledge Entities from Scientific Documents (EEKE)]
description: [Welcome to Workshop on Extraction and Evaluation of Knowledge Entities from Scientific Documents (EEKE)]
